// 自动生成：新浪财经滚动新闻（每日 pipeline 抓取）
// 分类与情绪标签为规则启发式（自动·仅供参考，非投资建议）；抓取于 2026-08-19
window.NEWS_DEEP = [
  {
    "category": "内地",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "08:55",
    "title": "直击WRC丨对话小米机器人总经理向迪昀：两年前“铁大”时速已超12km，但我们选了另一条路",
    "summary": "新浪科技讯 8月19日下午消息，2026世界机器人大会（WRC 2026）上，小米新一代人形机器人“铁大”首次亮相展会。该款机器人身高约1.70米，体重66公斤，全身拥有66个自由度...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/jjxw/2026-08-19/doc-ininvwqk8313155.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "08:48",
    "title": "快手：二季度总收入355亿元，经调整净利润39亿元",
    "summary": "新浪科技讯 8月19日下午消息，快手科技发布第二季度业绩。财报显示，2026年第二季度，快手总收入达到355亿元，同比增长1.4%，经调整净利润达39亿元，同比下降30.3%。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/jjxw/2026-08-19/doc-ininvwqk8307727.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "08:40",
    "title": "App崩溃风波后，奕境汽车又被曝给车主发假冒labubu，客服回应",
    "summary": "新浪科技讯 8月19日下午消息，近日有车主反映称，参加南昌当地奕境X9预售发布会，签到礼品可以选择领取labubu盲盒一个，拆开后却发现是假labubu。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/jjxw/2026-08-19/doc-ininvwqs2605013.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "08:38",
    "title": "AI时代，声音如何成为「声产力」？韶音OpenFit 2 AI媒体沟通会举行",
    "summary": "8月18日，全球领先的开放式耳机品牌Shokz韶音于上海举办OpenFit 2 AI媒体沟通会。本次沟通会以“AI时代，声音如何成为‘声产力’”为主题展开，韶音中国区品牌营销总监刘雅婷...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/tech/mobile/n/n/2026-08-19/doc-ininvwqs2603134.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "金融市场",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "07:59",
    "title": "直击WRC丨京东零售具身智能业务负责人郑小丹：京东已在北上广深等地推出“机器人救护车”等售后服务",
    "summary": "新浪科技讯 8月19日下午消息，2026世界机器人大会（WRC 2026）期间，京东零售具身智能业务负责人郑小丹对新浪科技表示，今年以来...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/jjxw/2026-08-19/doc-ininvwqt9349483.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "金融市场",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "07:43",
    "title": "宇树科技上市庆功照流出，“投资教父”沈南鹏露面",
    "summary": "新浪科技讯 8月19日下午消息，据报道，今日，“A股人形机器人第一股”宇树科技正式在科创板挂牌上市。截至当日收盘，宇树科技涨460.34%，报845元/股。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/jjxw/2026-08-19/doc-ininvshr7108887.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "07:41",
    "title": "8个月连续完成4轮融资，魔芯科技最新一轮融资规模5亿元",
    "summary": "新浪科技讯 8月19日下午消息，致力于4D世界模型研发和应用的魔芯科技，日前完成了新一轮5亿元人民币融资。分析显示，其公司估值已跃升至近40亿元人民币。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/jjxw/2026-08-19/doc-ininvshn8379168.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "金融市场",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "07:41",
    "title": "同有科技亏损多年后抛出近10亿募资计划 中小股东为何投下反对票？",
    "summary": "出品：新浪财经上市公司研究院 作者：郝显 8月13日，同有科技宣布2026年度向特定对象发行A股股票申请已获深交所受理。公司拟募集不超过9.998亿元...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/observe/2026-08-19/doc-ininvshu2694574.shtml",
    "sentiment": "negative",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "06:41",
    "title": "直击WRC丨星动纪元物流机器人现场拣快递，最快2000件/小时",
    "summary": "新浪科技讯 8月19日下午消息，今日，世界机器人大会（WRC 2026）于北京北人亦创国际会展中心开幕。 开展首日，星动纪元研发的物流分拣具身机器人上演了高效分拣快递的一幕...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/tech/2026-08-19/doc-ininvshr7054191.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "06:25",
    "title": "宝莱特易主“一周游”后第二大股东进驻董事会 毛利率持续下滑、四年亏损2.6亿、可转债偿付压力逼近",
    "summary": "出品：新浪财经上市公司研究院 作者：渚 一场被市场寄予厚望的“跨界救赎”，以闪电般的速度宣告“破产”。 2026年8月9日晚间，宝莱特发布公告...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/observe/2026-08-19/doc-ininvshv9418239.shtml",
    "sentiment": "negative",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "06:13",
    "title": "直击WRC丨宇树科技亮相2026世界机器人大会，G1款机器人现场展示乒乓球、舞蹈、格斗等运动",
    "summary": "新浪科技讯 8月19日下午消息，2026世界机器人大会（WRC 2026）期间，宇树科技携多款最新发布的人形机器人、四足机器人亮相大会，通过多类型机器人协同演示...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/tech/2026-08-19/doc-ininvshn8305415.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "05:51",
    "title": "直击WRC丨拳拳到肉！众擎机器人现场对打，旋风踢惊呆观众",
    "summary": "新浪科技讯 8月19日下午消息，今日，世界机器人大会（WRC 2026）于北京北人亦创国际会展中心正式开启。 展会首日，两台众擎T800机器人进行现场格斗，拳拳到肉，极限攻防...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/tech/2026-08-19/doc-ininvshr7017622.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-01",
    "dateCN": "8月1日",
    "time": "02:04",
    "title": "从激战赤水河到奋进强军路 电影《四渡》感动观众",
    "summary": "2026年8月1日，中国人民解放军迎来建军99周年。在这个承载着荣光与使命的节点，重大革命历史题材影片《四渡》正在全国热映——作为纪念红军长征胜利90周年...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/zz/2026-08-03/doc-inikumqh9029123.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-07-30",
    "dateCN": "7月30日",
    "time": "15:26",
    "title": "影迷评《年会不能停2！》笑点密集 轻松解压",
    "summary": "新浪娱乐讯 7月29日，小浪带领北京团员观看了电影《年会不能停2！》。影片讲述了当“天选之子”刘奔（张若昀 饰）遇上“天降搭子”马杰（白客 饰），这对天选“刘马”联手上阵...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/c/2026-07-30/doc-inikrfcx1138928.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-07-26",
    "dateCN": "7月26日",
    "time": "09:55",
    "title": "微博观影团《年会不能停2！》北京首映抢票",
    "summary": "特别提示： 本活动可以携带一名友人参加，好友也需提交观后感并携带本人身份证签到 活动流程 [活动日期]7月29日（周三） [签到时间]11：25-12：25 [观影时间...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/c/2026-07-26/doc-inikcpwf0444185.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-07-17",
    "dateCN": "7月17日",
    "time": "13:36",
    "title": "影迷评《八仙！》：笑点密集 反转不断",
    "summary": "新浪娱乐讯 7月15日，小浪带领北京团员观看了电影《八仙！》。“八仙”在成仙和成功之间选择了“成团”，在搞钱和搞事业之间选择了“搞事情”？！",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/c/2026-07-17/doc-iniicqkx8241449.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-07-13",
    "dateCN": "7月13日",
    "time": "11:17",
    "title": "微博观影团《八仙！》北京首映免费抢票",
    "summary": "活动流程 [活动日期]7月16日（周四） [签到时间]13：20-14：20 [观影时间]14：20-16：44 [映后互动]16：44-17：04 出席主创：（具体到场人员以当天出席为准） 活动影城：...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/c/2026-07-13/doc-inihsita5665135.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-07-08",
    "dateCN": "7月8日",
    "time": "03:11",
    "title": "电影《四渡》票房突破2亿 创长征题材票房新纪录",
    "summary": "以红军长征中四渡赤水战役为背景的重大革命历史题材影片《四渡》，自6月26日全国公映以来，多日蝉联单日票房冠军，在全国院线掀起了一股红色观影热潮...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/zz/2026-07-08/doc-inihaieh4810365.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-07-08",
    "dateCN": "7月8日",
    "time": "02:52",
    "title": "影迷评《三国第一部：争洛阳》：群雄逐鹿燃乱世",
    "summary": "新浪娱乐讯 7月5日，小浪带领北京团员观看了电影《三国第一部：争洛阳》。三国三部曲讲述东汉末年群雄逐鹿，终于赤壁一战，天下三分。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/c/2026-07-08/doc-inihaawk4917299.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-07-01",
    "dateCN": "7月1日",
    "time": "08:51",
    "title": "微博观影团《三国第一部：争洛阳》首映抢票",
    "summary": "活动流程 [活动日期]7月5日（周日） [签到时间]13：00-14：00 [观影时间]14：00-16：17 [映后互动]16：17-16：37 出席主创：（具体到场人员以当天出席为准） 制片人 导演...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/c/2026-07-01/doc-inifhvwy3107820.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-06-29",
    "dateCN": "6月29日",
    "time": "18:48",
    "title": "《挽救计划》全球票房将破7亿 上佳口碑后劲十足",
    "summary": "新浪娱乐讯 北京时间6月30日消息，据外国媒体报道，热门好评科幻片《挽救计划》全球票房已接近7亿美元，累计6.83亿，其中北美3.44亿，北美外3.39亿。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/f/2026-06-30/doc-inifcews3718933.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-06-29",
    "dateCN": "6月29日",
    "time": "18:16",
    "title": "《超级少女》票房表现灾难 口碑同遭滑铁卢",
    "summary": "新浪娱乐讯 北京时间6月30日消息，据外国媒体报道，DC新片《超级少女》中国内地首周/三天票房590万元，北美首周粗报3800万美元，全球首周6800万美元，皆低于预期。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/f/2026-06-30/doc-inifcews3702573.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-06-29",
    "dateCN": "6月29日",
    "time": "06:24",
    "title": "电影《四渡》青春特辑 解锁长征路上的青春模样",
    "summary": "四渡赤水，是长征史上极富传奇色彩的军事篇章。正在热映的电影《四渡》清晰还原了这场“用兵如神”的战役全貌，同时也把最滚烫的笔触，留给了冲锋在一线的红军战士们。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/zz/2026-06-29/doc-inifackz0275051.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-06-27",
    "dateCN": "6月27日",
    "time": "11:19",
    "title": "影迷评《四渡》：史诗级震撼",
    "summary": "新浪娱乐讯 6月25日，小浪带领北京团员观看了电影《四渡》。影片讲述了长征时期，红军身处绝境。四渡赤水堪称红军的绝地反击之战。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/c/2026-06-27/doc-inievzuq4588099.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "金融市场",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "09:02",
    "title": "光大期货0819热点追踪：供给端多重收紧，焦煤领涨黑色系",
    "summary": "周三，焦煤再度成为黑色系板块的领涨品种。焦煤2701合约收日内最大涨幅超2%；焦煤2609合约同步走强，涨幅也在2%之上。资金面上，截至发稿前...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/money/future/fmnews/2026-08-19/doc-ininvwqk8319364.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "金融市场",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "09:01",
    "title": "中天期货:橡胶震荡上行 棕榈五连阳",
    "summary": "热点品种分析 一、商品指数 二、股指 中国上证综指 8 月 19 日（周三）收盘下跌 95.88 点，跌幅 2.40%，报 3894.42 点； 中国深证成指 8 月 19 日（周三）收盘下跌 732...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/money/future/fmnews/2026-08-19/doc-ininvwqt9391727.shtml",
    "sentiment": "negative",
    "auto": true
  },
  {
    "category": "国际",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "09:00",
    "title": "特朗普将原定对加拿大实施的50%关税暂停三天，宣布与渥太华达成“协议”",
    "summary": "核心要点美国当地时间周二晚间，总统唐纳德・特朗普宣布暂缓对部分加拿大进口商品征收 50% 关税。媒体报道称，在美国准备对大批加拿大商品开征新关税前夕...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-19/doc-ininvwqk8316910.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "08:59",
    "title": "超级厄尔尼诺步步逼近 为何威胁全球粮食与能源安全",
    "summary": "厄尔尼诺现象卷土重来，而且可能演变成有记录以来最强的一次。其引发的极端天气不仅威胁粮食生产和能源供应，也可能推高通胀并拖累全球经济增长。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/world/2026-08-19/doc-ininvwqt9390670.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "08:56",
    "title": "光大期货0819热点追踪：烧碱底部抬升，反弹格局能否持续？",
    "summary": "光大期货0819热点追踪：烧碱底部抬升，反弹格局能否持续？",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/money/future/fmnews/2026-08-19/doc-ininvwqp7042599.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "国际",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "08:55",
    "title": "据报道伊朗考虑袭击欧洲境内美国目标，阿联酋切断对伊朗贸易",
    "summary": "核心要点《金融时报》周三报道，伊朗官员已在考量打击部署在欧洲的美国军事资产的可能性。美国总统特朗普周二证实，美伊谈判已经破裂，双方对峙陷入充满变数的僵局。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-19/doc-ininvwqp7041765.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "国际",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "08:53",
    "title": "美银调查：印度股市超越印尼，成为亚洲最不受青睐市场",
    "summary": "美国银行面向基金经理开展的一项调查显示，印度取代印尼成为亚洲最不受偏好的股票市场，反映出投资者对这一今年全球表现垫底的股市愈发谨慎。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-19/doc-ininvwqt9386900.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "宏观政策",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "08:52",
    "title": "直面英国严峻的经济现实",
    "summary": "核心要点过去 15 个月，英国经济始终难以实现持续增长，首相安迪・伯纳姆与财政大臣约翰・希利因此面临艰难抉择。尽管国内经济表现疲弱，但受益于成分股大量布局海外业务...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-19/doc-ininvwqp7039107.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "国际",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "08:48",
    "title": "SK海力士ADR盘前大涨 受该公司290亿美元的股票回购计划提振",
    "summary": "SK海力士的美国存托凭证（ADR）在周三盘前交易中一度上涨7.3%。此前该公司宣布计划回购40万亿韩元（290亿美元）的自家股票，以缓解投资者对AI支出可持续性的担忧。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-19/doc-ininvwqp7035726.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "国际",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "08:47",
    "title": "【点石成金】美债利率扰动：流动性范式切换与组合配置应对",
    "summary": "国投期货研究院 一、全球资产定价主线——美债期限溢价重构 今年以来全球大类资产走势越发复杂，市场交易核心驱动更偏向于美债长端供需结构失衡与期限溢价定价...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/money/future/2026-08-19/doc-ininvwqs2610733.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "宏观政策",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "08:43",
    "title": "长安期货刘琳：现货低点逐步抬升 中短期猪价上行空间仍受限",
    "summary": "核心观点： 当前生猪市场正处于“弱现实”与“强预期”博弈的关键阶段。短期看，肥标价差超预期走扩与能繁母猪存栏降至政策红线附近，为市场提供了阶段性的底部支撑...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/money/future/2026-08-19/doc-ininvwqs2607044.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "国际",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "08:43",
    "title": "等待FOMC会议纪要出炉，美债收益率从数十年来高点回落",
    "summary": "周三，美国国债收益率较前一日创下的数十年高点小幅回落，长端债券的抛售潮有所缓和，投资者焦虑情绪得到缓解。 作为美国政府融资关键基准的 10 年期美债收益率下跌 2...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-19/doc-ininvwqs2606783.shtml",
    "sentiment": "negative",
    "auto": true
  },
  {
    "category": "港股",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "08:42",
    "title": "上市物业公司炒贵金属上半年亏8340万元，年初曾狂赚2.5亿",
    "summary": "曾因投资贵金属狂赚2.5亿的港股上市公司祈福生活服务（03686.HK）近日发布盈利警告称，集团预期于2026年上半年将录得公司拥有人应占亏损及综合亏损总额介乎于240万元至440...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/s/2026-08-19/doc-ininvwqt9384214.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "08:40",
    "title": "收购战打响，竞争对手竞相入局，全球最大橄榄油企业股价暴涨17%",
    "summary": "核心要点 有报道称，西班牙农业食品合作社集团 Dcoop 出价 4.7 亿欧元（折合 5.45 亿美元）收购 Deoleo，受此消息影响，该股出现大幅上涨。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-19/doc-ininvwqk8299817.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "金融市场",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "08:36",
    "title": "亚洲“黑色星期三” 背后发生了什么？",
    "summary": "来源：中国基金报 记者 泰勒 大家好啊，今天亚洲“黑色星期三”，AI产业链全线暴跌，7月份的痛苦回忆再次涌上心头，一起找找原因吧。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/money/future/fmnews/2026-08-19/doc-ininvwqs2602708.shtml",
    "sentiment": "negative",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "08:35",
    "title": "万亿固收资金负责人变动，人保资产固收投资总经理被免",
    "summary": "近日，有市场消息称，中国人保资产管理有限公司（简称“人保资产”）固定收益投资部总经理‌刘毅或被免职。21世纪经济报道记者从知情人士处了解到，该消息属实...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/roll/2026-08-19/doc-ininvwqs2603754.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "08:25",
    "title": "七夕送礼帮对方 “拔草”！分期乐商城数据：3C 产品销量迎来小爆发",
    "summary": "临近七夕，小鱼偷偷在分期乐商城下单了一台大疆Pocket 3，准备送给女朋友。与其说这是他专门挑选的七夕礼物，不如说他终于找到一个理由...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/enterprise/2026-08-19/doc-ininvwqp7016324.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "08:11",
    "title": "OpenAI二季度营收增长乏力，表现不及Anthropic",
    "summary": "OpenAI向投资者透露，公司第二季度营收较第一季度增长18%，但亏损进一步扩大。部分股东对此结果感到失望，他们原本期待这家初创企业能在追赶竞争对手Anthropic方面取得更大...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-19/doc-ininvwqs2585935.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "宏观政策",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "08:09",
    "title": "欧洲央行分析师：人工智能行情之后出现估值回调是大概率事件",
    "summary": "欧洲央行五名研究人员于8月17日在官方博客发表《人工智能繁荣：理性热情还是下一个互联网泡沫？》。作者为Malin Andersson、Johannes Breckenfelder、Stefano Corradin...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-19/doc-ininvwqp7003639.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "08:05",
    "title": "破财免灾：苹果调整欧盟应用商店费率以了结数字市场法案争端",
    "summary": "苹果周二宣布，经与欧盟委员会密切磋商，统一欧盟地区应用分发商务条款，并于10月1日生效。开发者即日起可签署新协议。核心技术费（Core Technology...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-19/doc-ininvwqs2580881.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "国际",
    "date": "2026-08-19",
    "dateCN": "8月19日",
    "time": "08:02",
    "title": "美国联邦债务预计本周突破40万亿美元，早于国会预算办公室原测算",
    "summary": "彼得·彼得森基金会债务追踪器与财政部财政数据面板显示，截至本周二，美国联邦债务总额约39.9万亿美元。参议院联合经济委员会8月5日口径为39.83万亿美元，其中公众持有32...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-19/doc-ininvwqp6996399.shtml",
    "sentiment": "neutral",
    "auto": true
  }
];