// 自动生成：新浪财经滚动新闻（每日 pipeline 抓取）
// 分类与情绪标签为规则启发式（自动·仅供参考，非投资建议）；抓取于 2026-08-12
window.NEWS_DEEP = [
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "09:34",
    "title": "2027款海豹06上市：纯电续航最高630km，闪充智驾齐上车，售价9.99万元起",
    "summary": "新浪科技讯 8月12日下午消息，比亚迪海洋网B级家轿——2027款海豹06正式上市，提供纯电和插电混动双动力版本，共12个款型，官方指导价为9.99万元-15.59万元。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/jjxw/2026-08-12/doc-inimzytr4052005.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "09:32",
    "title": "腾讯控股：第二季度录得负自由现金流人民币138亿元",
    "summary": "新浪科技讯 8月12日下午消息，腾讯控股公告，第二季，本集团录得负自由现金流人民币138亿元，此乃由于经营活动所产生的现金净额人民币527亿元...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/jjxw/2026-08-12/doc-inimzytm3651956.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "09:23",
    "title": "AI没有“干掉”办公软件，反而正引发新一轮竞赛",
    "summary": "21世纪经济报道记者骆轶琪 “AI会不会吞噬软件？”在今年年初成为备受业界关注的话题之一。 这源于Anthropic发布Claude Cowork、OpenAI发布Codex所引发的一种研判：这些从基...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/roll/2026-08-12/doc-inimzytn5321561.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "08:59",
    "title": "波兰敦促SpaceX恢复波兰用户星链漫游服务",
    "summary": "波兰数字事务部长克日什托夫・加科夫斯基在X平台发文表示，波兰已要求SpaceX将本国重新纳入星链漫游服务的欧洲区域范围，称近期的归类调整缺乏合理性...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/world/2026-08-12/doc-inimzytn5301641.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "08:57",
    "title": "腾讯Q2财报：云业务增长提速，研发投入同比增长 35%达 273 亿元",
    "summary": "新浪科技讯 8 月 12 日下午消息，腾讯发布 2026 年Q2财报。本季度，腾讯实现营收 2048亿元；其中，金融科技及企业服务收入 603亿元，同比增长 9%。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/jjxw/2026-08-12/doc-inimzytm3631719.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "08:45",
    "title": "腾讯Q2营收2047.9亿元，同比增长11%",
    "summary": "新浪科技讯 8月12日下午消息，今日，腾讯控股发布二季报，期内腾讯营收2047.9亿元，同比增长11%；Non-IFRS经营利润756.4亿元，同比增长9%；若剔除新AI产品影响...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/jjxw/2026-08-12/doc-inimzytm3624247.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "08:39",
    "title": "机构称长江存储市占率首次跻身全球第三",
    "summary": "8月12日，市场研究机构Counterpoint发布数据称，2026年第二季度NAND闪存市场以出货量计算，三星、SK海力士、长江存储的份额分别为25%、22%、14%...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/jjxw/2026-08-12/doc-inimzytn5289519.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "07:32",
    "title": "小红书RED LAND 2026官宣十月开幕：集结超百个热门IP，探索区域扩至10万平方米",
    "summary": "新浪科技讯 8月12日下午消息，今日，小红书宣布，RED LAND 2026将于10月2日至6日在上海杨浦复兴岛举办，这是RED LAND连续第二年落地复兴岛。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/jjxw/2026-08-12/doc-inimzytr3967197.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "06:48",
    "title": "寒武纪“三年千亿”军令状背后：业绩翻倍现金却只收回零头 近半数资产都是存货跌价损失创历史新高",
    "summary": "出品：新浪财经上市公司研究院 作者：渚 2026年8月7日晚，寒武纪交出了一份令市场瞩目的半年报：上半年营业收入59.96亿元，同比增长108.13%；归母净利润23.11亿元...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/observe/2026-08-12/doc-inimzumq5332849.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "06:29",
    "title": "Salomon萨洛蒙北京国贸商城旗舰店正式揭幕 | 贵圈",
    "summary": "8月12日消息，近日，法国专业户外运动品牌Salomon萨洛蒙“Blue Perspective多元之蓝”主题摄影艺术展率先于Salomon萨洛蒙北京国贸商城旗舰店盛大启幕。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/tech/shenji/2026-08-12/doc-inimzumq5318068.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "05:26",
    "title": "星巴克再回应“蜜雪冰城将代工多款物料”：信息严重失实！",
    "summary": "8月12日，有报道称，前山姆中国CMO张青加入博裕资本负责操刀星巴克中国供应链改革，包括寻求与其他供应商合作，降低物料成本等，如纸杯、吸管...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/tech/shenji/2026-08-12/doc-inimzump3624883.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "金融市场",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "04:54",
    "title": "“DeepSeek Harness团队”公众号上线，IP属地北京",
    "summary": "新浪科技讯 8月11日午间消息，“DeepSeek Harness团队”微信公众号近期完成注册。该公众号认证主体为北京深度求索人工智能基础技术研究有限公司，IP属地北京海淀...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/tob/2026-08-12/doc-inimzqcs5391945.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-01",
    "dateCN": "8月1日",
    "time": "02:04",
    "title": "从激战赤水河到奋进强军路 电影《四渡》感动观众",
    "summary": "2026年8月1日，中国人民解放军迎来建军99周年。在这个承载着荣光与使命的节点，重大革命历史题材影片《四渡》正在全国热映——作为纪念红军长征胜利90周年...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/zz/2026-08-03/doc-inikumqh9029123.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-07-30",
    "dateCN": "7月30日",
    "time": "15:26",
    "title": "影迷评《年会不能停2！》笑点密集 轻松解压",
    "summary": "新浪娱乐讯 7月29日，小浪带领北京团员观看了电影《年会不能停2！》。影片讲述了当“天选之子”刘奔（张若昀 饰）遇上“天降搭子”马杰（白客 饰），这对天选“刘马”联手上阵...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/c/2026-07-30/doc-inikrfcx1138928.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-07-26",
    "dateCN": "7月26日",
    "time": "09:55",
    "title": "微博观影团《年会不能停2！》北京首映抢票",
    "summary": "特别提示： 本活动可以携带一名友人参加，好友也需提交观后感并携带本人身份证签到 活动流程 [活动日期]7月29日（周三） [签到时间]11：25-12：25 [观影时间...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/c/2026-07-26/doc-inikcpwf0444185.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-07-17",
    "dateCN": "7月17日",
    "time": "13:36",
    "title": "影迷评《八仙！》：笑点密集 反转不断",
    "summary": "新浪娱乐讯 7月15日，小浪带领北京团员观看了电影《八仙！》。“八仙”在成仙和成功之间选择了“成团”，在搞钱和搞事业之间选择了“搞事情”？！",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/c/2026-07-17/doc-iniicqkx8241449.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-07-13",
    "dateCN": "7月13日",
    "time": "11:17",
    "title": "微博观影团《八仙！》北京首映免费抢票",
    "summary": "活动流程 [活动日期]7月16日（周四） [签到时间]13：20-14：20 [观影时间]14：20-16：44 [映后互动]16：44-17：04 出席主创：（具体到场人员以当天出席为准） 活动影城：...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/c/2026-07-13/doc-inihsita5665135.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-07-08",
    "dateCN": "7月8日",
    "time": "03:11",
    "title": "电影《四渡》票房突破2亿 创长征题材票房新纪录",
    "summary": "以红军长征中四渡赤水战役为背景的重大革命历史题材影片《四渡》，自6月26日全国公映以来，多日蝉联单日票房冠军，在全国院线掀起了一股红色观影热潮...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/zz/2026-07-08/doc-inihaieh4810365.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-07-08",
    "dateCN": "7月8日",
    "time": "02:52",
    "title": "影迷评《三国第一部：争洛阳》：群雄逐鹿燃乱世",
    "summary": "新浪娱乐讯 7月5日，小浪带领北京团员观看了电影《三国第一部：争洛阳》。三国三部曲讲述东汉末年群雄逐鹿，终于赤壁一战，天下三分。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/c/2026-07-08/doc-inihaawk4917299.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-07-01",
    "dateCN": "7月1日",
    "time": "08:51",
    "title": "微博观影团《三国第一部：争洛阳》首映抢票",
    "summary": "活动流程 [活动日期]7月5日（周日） [签到时间]13：00-14：00 [观影时间]14：00-16：17 [映后互动]16：17-16：37 出席主创：（具体到场人员以当天出席为准） 制片人 导演...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/c/2026-07-01/doc-inifhvwy3107820.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-06-29",
    "dateCN": "6月29日",
    "time": "18:48",
    "title": "《挽救计划》全球票房将破7亿 上佳口碑后劲十足",
    "summary": "新浪娱乐讯 北京时间6月30日消息，据外国媒体报道，热门好评科幻片《挽救计划》全球票房已接近7亿美元，累计6.83亿，其中北美3.44亿，北美外3.39亿。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/f/2026-06-30/doc-inifcews3718933.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-06-29",
    "dateCN": "6月29日",
    "time": "18:16",
    "title": "《超级少女》票房表现灾难 口碑同遭滑铁卢",
    "summary": "新浪娱乐讯 北京时间6月30日消息，据外国媒体报道，DC新片《超级少女》中国内地首周/三天票房590万元，北美首周粗报3800万美元，全球首周6800万美元，皆低于预期。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/f/2026-06-30/doc-inifcews3702573.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-06-29",
    "dateCN": "6月29日",
    "time": "06:24",
    "title": "电影《四渡》青春特辑 解锁长征路上的青春模样",
    "summary": "四渡赤水，是长征史上极富传奇色彩的军事篇章。正在热映的电影《四渡》清晰还原了这场“用兵如神”的战役全貌，同时也把最滚烫的笔触，留给了冲锋在一线的红军战士们。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/zz/2026-06-29/doc-inifackz0275051.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-06-27",
    "dateCN": "6月27日",
    "time": "11:19",
    "title": "影迷评《四渡》：史诗级震撼",
    "summary": "新浪娱乐讯 6月25日，小浪带领北京团员观看了电影《四渡》。影片讲述了长征时期，红军身处绝境。四渡赤水堪称红军的绝地反击之战。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/c/2026-06-27/doc-inievzuq4588099.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "09:24",
    "title": "中矿资源津巴布韦年产10万吨硫酸锂项目全面开工",
    "summary": "转自：证券时报 人民财讯8月12日电，据中矿资源消息，近日，中矿资源所属津巴布韦马辛戈锂业科技有限公司正式获得津巴布韦环境管理机构Environmental Management...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/jjxw/2026-08-12/doc-inimzytn5319982.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "国际",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "09:22",
    "title": "美联储9月加息悬念迎胜负手，全场盯紧CPI这一“生死线”！",
    "summary": "文章来源：金十数据 在美联储9月加息概率五五开之际，7月CPI只需稍微偏离预期就能扭转局面。市场焦点不在通胀是否下降，而是通胀能否不靠加息回归2%目标...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/roll/2026-08-12/doc-inimzytm3650971.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "09:22",
    "title": "快讯：现货白银日内涨3%，现报66.59美元/盎司",
    "summary": "北京时间8月12日下午，现货白银日内涨3%，现报66.59美元/盎司。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/money/nmetal/hjzx/2026-08-12/doc-inimzytr4044768.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "09:22",
    "title": "560元！江波龙溢价定增，新老高管“用脚投票唱反调”",
    "summary": "来源：尺度商业 文 | 张佳儒 编辑 | 刘振涛 你敢信吗？上市公司前高管们抢着给公司送钱，可公司的现任高管们却忙着套现离场，这是啥情况？",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/s/2026-08-12/doc-inimzyti6875476.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "金融市场",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "09:18",
    "title": "Situational Awareness披露持股太阳诱电 股价应声上涨",
    "summary": "根据人工智能对冲基金Situational Awareness提交的多份文件，该基金于6月底买入日本服务器零部件制造商太阳诱电的股票，并一度将持股比例提高至16.61%，之后又减持。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-12/doc-inimzytm3644248.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "09:09",
    "title": "【玉米专题】玉米见底了吗？",
    "summary": "紫金天风期货 观点小结 7月以来玉米现货价格呈现持续偏弱震荡，一方面是相关替代品充裕，特别是小麦今年整体丰收，现货价格持续走弱，饲用替代优势明显...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/money/future/2026-08-12/doc-inimzyti6871501.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "09:09",
    "title": "豆菜粕：盘面退升水 关注8月USDA报告",
    "summary": "紫金天风期货 观点小结 核心观点：震荡 美伊就霍尔木兹海峡重开谈判陷入僵局。市场聚焦北京时间周四凌晨USDA8月供需报告，本次报告将首次结合农户调查和客观测产数据...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/money/future/2026-08-12/doc-inimzyti6871394.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "09:09",
    "title": "Hello Kitty热度难挡股价跳水：三丽鸥财报出炉，股价暴跌 18%",
    "summary": "核心要点凯蒂猫（Hello Kitty）母公司三丽鸥公布财年一季度业绩后，东京市场该股周三大跌 18%；而财报发布前，股价已经经历一轮大幅上涨。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-12/doc-inimzytm3638905.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "09:08",
    "title": "国际能源署：战争冲击需求，但石油供应缺口进一步扩大",
    "summary": "国际能源署称，伊朗冲突再度升级，尽管高油价对需求的打击持续加剧，但本季度全球石油库存的下滑幅度将远超此前预期，达到原先预估的两倍多。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/world/2026-08-12/doc-inimzyti6865795.shtml",
    "sentiment": "negative",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "09:07",
    "title": "LME铜库存连续40天下降 创2014年以来最长纪录",
    "summary": "伦敦金属交易所（LME）仓库网络中的铜库存已连续40天下降，是2014年初以来的最长连降纪录。 库存已较5月中旬下降近50%，至212125吨。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/world/2026-08-12/doc-inimzytn5307498.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "09:06",
    "title": "普京表态：倘若欧盟各国扣押俄罗斯船只，俄罗斯将采取对等反制措施",
    "summary": "俄罗斯总统普京周三表态：倘若欧盟各国扣押俄罗斯商船，俄方将采取对等反制措施。 此番言论出台背景是：欧盟正对俄罗斯所谓影子船队加大施压力度...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-12/doc-inimzytr4034425.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "09:05",
    "title": "国际能源署：沙特、伊拉克和伊朗7月原油产量增加 阿联酋下降",
    "summary": "国际能源署（IEA）在月度报告中称，沙特、伊拉克、科威特和伊朗7月石油产量环比增加，而阿联酋产量在该地区航运遭袭后有所下降。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/world/2026-08-12/doc-inimzytn5305720.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "09:20",
    "title": "获5亿元大补血！晋商消金增资至10亿元",
    "summary": "原标题：获5亿元大补血！这家消金公司增资至10亿元 近日，晋商消费金融股份有限公司（下称“晋商消金”）增资扩股方案正式获得监管批复。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/zqgd/2026-08-12/doc-inimzytr4045381.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "09:07",
    "title": "债+股双重“补血”，江西银行“破例”启动9.3亿股定增，去年营收同比下降21.89％",
    "summary": "华夏时报记者张萌 北京报道 日前，江西银行（01916.HK）接连发布多份公告，密集推进资本补充计划。 一方面，江西银行获江西金融监管局批复...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/roll/2026-08-12/doc-inimzytm3641204.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "国际",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "09:07",
    "title": "“币圈大亨”叶俊德全裸坠亡，旗下管理资产24亿美元",
    "summary": "据多个加密货币社区消息，当地时间8月7日凌晨2时左右，华裔加密货币投资人叶俊德在南美国家巴拉圭首都的30层豪华公寓“Jade Park”坠楼身亡。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/jjxw/2026-08-12/doc-inimzytr4035312.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "金融市场",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "09:04",
    "title": "全球最大主权财富基金斩获创纪录1840亿美元利润，首次披露持有SpaceX股份",
    "summary": "核心要点规模达 2.3 万亿美元的挪威主权财富基金周三公布，上半年盈利突破 1840 亿美元，创下历史新高。基金同时对外披露持有 SpaceX 0.05% 股权，对应估值约 12 亿美元。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-12/doc-inimzytn5305604.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "09:02",
    "title": "阿联酋据悉提出采用短途转运策略 将伊拉克原油运出霍尔木兹海峡",
    "summary": "据知情人士透露，阿布扎比国家石油公司提出利用其隐蔽的的短途转运策略，可将巴士拉等伊拉克原油经由霍尔木兹海峡运往亚洲炼油厂。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/world/2026-08-12/doc-inimzytm3634710.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "09:02",
    "title": "Aviva实现惊人复苏，一大悬念尚存：下一步怎么走？",
    "summary": "核心要点Aviva是英国散户持仓规模最大的个股之一，本土客户数量达 2200 万，本周将公布业绩。在股价数十年表现低迷后，阿曼达・布朗克对Aviva实施业务精简...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-12/doc-inimzytr4031015.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "金融市场",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "09:01",
    "title": "咖哩猪排指数显示日元严重低估 创建人称比巨无霸指数更贴切",
    "summary": "随着当局干预汇市的影响正在消退，纽约梅隆银行一位高级策略师利用日本一道快餐主食的价格，以准确衡量日元的疲弱程度。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/world/2026-08-12/doc-inimzyti6861337.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-12",
    "dateCN": "8月12日",
    "time": "08:59",
    "title": "巴基斯坦：内政部长向伊朗领导人传递一则“特殊且重要”信息",
    "summary": "巴基斯坦内政部周三发表声明称，内政部长Mohsin Naqvi向伊朗领导人转达了总理夏巴兹·谢里夫和陆军参谋长Asim Munir关于该地区当前局势的“特殊且重要的信息”。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/world/2026-08-12/doc-inimzyti6860055.shtml",
    "sentiment": "neutral",
    "auto": true
  }
];