// 自动生成：新浪财经滚动新闻（每日 pipeline 抓取）
// 分类与情绪标签为规则启发式（自动·仅供参考，非投资建议）；抓取于 2026-08-04
window.NEWS_DEEP = [
  {
    "category": "内地",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "14:25",
    "title": "鸿蒙智行回应“竹知了”事件：针对的是侵权内容，并非“竹知了”玩具",
    "summary": "新浪科技讯 8月4日晚间消息，针对近期的“竹知了”事件，鸿蒙智行发言人今日发布《关于近期“竹知了”相关网络信息的情况说明》，称网络上持续存在恶意剪辑...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/jjxw/2026-08-04/doc-inimekpi1944751.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "12:01",
    "title": "嘀嗒出行：暑期顺风车跨城出游200公里以内下单超6成，短途周边游是主体",
    "summary": "新浪科技讯 8月4日晚间消息，2026暑期已过半，各地旅游热度持续升温。近日，嘀嗒出行发布《2026暑期顺风车短途周边游洞察》。基于顺风车大数据统计显示：暑期顺风车市内旅...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/jjxw/2026-08-04/doc-inimeefm2019641.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "11:53",
    "title": "菜鸟“关仓一体”英国仓正式运营",
    "summary": "新浪科技讯 8月4日晚间消息，8月3日，菜鸟英国伦敦口岸仓正式开仓运营。据介绍，此前该仓已历经数月试运营，“关仓一体”模式经实际业务检验，把清关、查验...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/jjxw/2026-08-04/doc-inimeeez4039754.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "11:23",
    "title": "瑞幸二季度营收159亿，健康专业化产品创新拉动高复购",
    "summary": "导语： CEO称：中国咖啡市场的门店天花板还非常高 8月3日晚，瑞幸咖啡公布2026年第二季度财报。本季度总净收入同比增长28.5%，约159亿元，营业利润同比增长22%，超21...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/tech/it/2026-08-04/doc-inimeefm2001357.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "金融市场",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "11:09",
    "title": "与Pura X比例近似 华为首款阔直板形态手机有望秋冬季问世",
    "summary": "自从去年华为阔折叠——华为Pura X系列发布之后，深受市场好评，不少厂商也开始跟进。而据据博主定焦数码透露，华为今年继续在产品形态方面实现创新...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/tech/roll/2026-08-04/doc-inimeefm1996426.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "10:30",
    "title": "金字火腿连续押注光模块电芯片：主业陷入亏损 核心产品销量下滑产能消化问题待解",
    "summary": "出品：新浪财经上市公司研究院 作者：郝显 7月30日晚间，金字火腿披露2026 年半年度报告，首次出现中报亏损。上半年实现营业收入1.54亿元，同比下降 9.26%；亏损812...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/observe/2026-08-04/doc-inimcxxf5721022.shtml",
    "sentiment": "negative",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "10:01",
    "title": "OPPO A7 Pro Max发布：搭载行业首个七年长寿万级大电池，售价2199元起",
    "summary": "新浪科技讯 8月4日下午消息，OPPO A系列全新产品A7 Pro Max正式发布，售价2199元起。OPPO A系列产品经理马俊表示：“作为全球8亿用户的耐用之选...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/tech/it/2026-08-04/doc-inimcxxp2094825.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "09:57",
    "title": "美图业绩预告超预期 瑞银、高盛给予“买入”评级",
    "summary": "新浪科技讯 8月4日下午消息，近日，美图公司发布2026上半年业绩预告，显示付费订阅用户数创新高，生产力应用ARR、AI算力点消费额快速增长。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/tech/it/2026-08-04/doc-inimcxxm5320701.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "09:38",
    "title": "小红书严打伪造文旅专业号身份黑产，配合各地警方抓捕4个作案团伙共计14人",
    "summary": "新浪科技讯 8月4日下午消息，近期全国迎来暑期出游高峰，小红书从严治理社区内文旅行业内容与经营生态，并主动移交黑灰产线索配合警方打击。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/jjxw/2026-08-04/doc-inimcxxp2084335.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "08:56",
    "title": "腾讯混元发布最新语音识别模型Hy ASR 3.0 preview",
    "summary": "新浪科技讯 8 月4日下午消息，腾讯混元正式发布新一代语音识别模型 Hy ASR 3.0 preview。基于最新一代大语言模型 Hy3 的语言理解能力，Hy ASR 3...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/jjxw/2026-08-04/doc-inimcxxm5288564.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "金融市场",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "08:12",
    "title": "每刻深思邹天琦：“光算光连”将是长期方向",
    "summary": "新浪科技讯 8月4日下午消息，如果说去年市场还在争论“算力够不够用”时，今年行业共识已经转向了另一个更棘手的问题——“算力用得起吗？",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/jjxw/2026-08-04/doc-inimctrp5397157.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "08:05",
    "title": "中止 3 年后，日本再次推进国产客机研发计划",
    "summary": "IT之家 8 月 4 日消息，据《日经》昨日报道，日本首款国产喷气式客机三菱 Space Jet（原 MRJ）计划中止已过去 3 年时间。如今日本政府希望吸取失败经验...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/tech/digi/2026-08-04/doc-inimcxxp2043230.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-01",
    "dateCN": "8月1日",
    "time": "02:04",
    "title": "从激战赤水河到奋进强军路 电影《四渡》感动观众",
    "summary": "2026年8月1日，中国人民解放军迎来建军99周年。在这个承载着荣光与使命的节点，重大革命历史题材影片《四渡》正在全国热映——作为纪念红军长征胜利90周年...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/zz/2026-08-03/doc-inikumqh9029123.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-07-30",
    "dateCN": "7月30日",
    "time": "15:26",
    "title": "影迷评《年会不能停2！》笑点密集 轻松解压",
    "summary": "新浪娱乐讯 7月29日，小浪带领北京团员观看了电影《年会不能停2！》。影片讲述了当“天选之子”刘奔（张若昀 饰）遇上“天降搭子”马杰（白客 饰），这对天选“刘马”联手上阵...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/c/2026-07-30/doc-inikrfcx1138928.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-07-26",
    "dateCN": "7月26日",
    "time": "09:55",
    "title": "微博观影团《年会不能停2！》北京首映抢票",
    "summary": "特别提示： 本活动可以携带一名友人参加，好友也需提交观后感并携带本人身份证签到 活动流程 [活动日期]7月29日（周三） [签到时间]11：25-12：25 [观影时间...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/c/2026-07-26/doc-inikcpwf0444185.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-07-17",
    "dateCN": "7月17日",
    "time": "13:36",
    "title": "影迷评《八仙！》：笑点密集 反转不断",
    "summary": "新浪娱乐讯 7月15日，小浪带领北京团员观看了电影《八仙！》。“八仙”在成仙和成功之间选择了“成团”，在搞钱和搞事业之间选择了“搞事情”？！",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/c/2026-07-17/doc-iniicqkx8241449.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-07-13",
    "dateCN": "7月13日",
    "time": "11:17",
    "title": "微博观影团《八仙！》北京首映免费抢票",
    "summary": "活动流程 [活动日期]7月16日（周四） [签到时间]13：20-14：20 [观影时间]14：20-16：44 [映后互动]16：44-17：04 出席主创：（具体到场人员以当天出席为准） 活动影城：...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/c/2026-07-13/doc-inihsita5665135.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-07-08",
    "dateCN": "7月8日",
    "time": "03:11",
    "title": "电影《四渡》票房突破2亿 创长征题材票房新纪录",
    "summary": "以红军长征中四渡赤水战役为背景的重大革命历史题材影片《四渡》，自6月26日全国公映以来，多日蝉联单日票房冠军，在全国院线掀起了一股红色观影热潮...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/zz/2026-07-08/doc-inihaieh4810365.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-07-08",
    "dateCN": "7月8日",
    "time": "02:52",
    "title": "影迷评《三国第一部：争洛阳》：群雄逐鹿燃乱世",
    "summary": "新浪娱乐讯 7月5日，小浪带领北京团员观看了电影《三国第一部：争洛阳》。三国三部曲讲述东汉末年群雄逐鹿，终于赤壁一战，天下三分。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/c/2026-07-08/doc-inihaawk4917299.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-07-01",
    "dateCN": "7月1日",
    "time": "08:51",
    "title": "微博观影团《三国第一部：争洛阳》首映抢票",
    "summary": "活动流程 [活动日期]7月5日（周日） [签到时间]13：00-14：00 [观影时间]14：00-16：17 [映后互动]16：17-16：37 出席主创：（具体到场人员以当天出席为准） 制片人 导演...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/c/2026-07-01/doc-inifhvwy3107820.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-06-29",
    "dateCN": "6月29日",
    "time": "18:48",
    "title": "《挽救计划》全球票房将破7亿 上佳口碑后劲十足",
    "summary": "新浪娱乐讯 北京时间6月30日消息，据外国媒体报道，热门好评科幻片《挽救计划》全球票房已接近7亿美元，累计6.83亿，其中北美3.44亿，北美外3.39亿。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/f/2026-06-30/doc-inifcews3718933.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-06-29",
    "dateCN": "6月29日",
    "time": "18:16",
    "title": "《超级少女》票房表现灾难 口碑同遭滑铁卢",
    "summary": "新浪娱乐讯 北京时间6月30日消息，据外国媒体报道，DC新片《超级少女》中国内地首周/三天票房590万元，北美首周粗报3800万美元，全球首周6800万美元，皆低于预期。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/f/2026-06-30/doc-inifcews3702573.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-06-29",
    "dateCN": "6月29日",
    "time": "06:24",
    "title": "电影《四渡》青春特辑 解锁长征路上的青春模样",
    "summary": "四渡赤水，是长征史上极富传奇色彩的军事篇章。正在热映的电影《四渡》清晰还原了这场“用兵如神”的战役全貌，同时也把最滚烫的笔触，留给了冲锋在一线的红军战士们。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/zz/2026-06-29/doc-inifackz0275051.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-06-27",
    "dateCN": "6月27日",
    "time": "11:19",
    "title": "影迷评《四渡》：史诗级震撼",
    "summary": "新浪娱乐讯 6月25日，小浪带领北京团员观看了电影《四渡》。影片讲述了长征时期，红军身处绝境。四渡赤水堪称红军的绝地反击之战。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://ent.sina.com.cn/m/c/2026-06-27/doc-inievzuq4588099.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "国际",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "16:16",
    "title": "美股强力拉升刷新纪录 伊朗考虑在霍尔木兹海峡做出让步",
    "summary": "美国股市周二扩大涨势，而油价和10年期国债收益率持续下跌，因伊朗据悉权衡允许欧洲国家清除霍尔木兹海峡的水雷。 当天早些时候，美国财政部长贝森特表示...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-05/doc-inimequx5522549.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "金融市场",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "16:13",
    "title": "欧洲股市创新高 强劲企业财报与中东停火预期提振市场",
    "summary": "欧洲股市创下历史新高，强劲的企业业绩、矿业股上涨以及市场对中东即将实现停火的乐观预期共同提振市场。 斯托克欧洲600指数收涨0.7%。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-05/doc-inimequv3917749.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "国际",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "16:12",
    "title": "一位投资策略专家与一位韩国牙医 挑战杠杆ETF传统玩法",
    "summary": "越来越多来自美国、韩国等地的投资者，正把杠杆型ETF用于长期投资，这与这类产品最初为日内交易设计的用途已大相径庭。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-05/doc-inimeqvf1848356.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "宏观政策",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "16:11",
    "title": "市场定价显示英国央行今年加息25个基点的可能性不再达到100%",
    "summary": "货币市场削减对英国央行进一步加息的押注，年底前加息25个基点的可能性不再达到100%。 这是自7月8日以来，市场认为加息25个基点的可能性首次低于100%。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-05/doc-inimeqvf1847914.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "国际",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "15:53",
    "title": "伊朗考虑允许欧洲参与霍尔木兹海峡排雷",
    "summary": "伊朗考虑允许欧洲国家清除霍尔木兹海峡的水雷，这一潜在的让步可能成为恢复海峡航运正常化协议的一部分，并有助于缓和与美国的和平谈判。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-04/doc-inimequx5511983.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "国际",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "15:46",
    "title": "欧洲债市：欧洲债券上涨 美伊协议预期推动油价下跌",
    "summary": "欧洲政府债券收益率全线下跌，因为卡塔尔表示，一项旨在重启美伊谈判的潜在协议“已经起草”，并且美国财长贝森特也对达成重开霍尔木兹海峡的协议表示乐观。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-04/doc-inimequv3905368.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "15:45",
    "title": "苹果公司请求法官即刻禁止OpenAI使用其商业秘密",
    "summary": "苹果公司在指控OpenAI有组织窃取其将发布产品的信息案中再次出击，请求联邦法官立即下令这家人工智能企业停止使用它所指的被窃商业秘密。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-04/doc-inimequv3905239.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "15:28",
    "title": "Anthropic与Volta达成100亿美元算力协议",
    "summary": "知情人士称，Anthropic PBC与成立仅数月的基础设施初创公司Volta Infra Holdings Ltd．达成一项价值100亿美元的算力协议，此举是这家Claude开发商为满足产品需求而采取的最...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-04/doc-inimequx5500572.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "15:22",
    "title": "SpaceX财报发布前夕 航天概念股普涨",
    "summary": "在马斯克旗下SpaceX公布上市以来首份财报前夕，火箭、卫星及其他航天概念股周二普遍上涨。 航天与国防公司Voyager Technologies表现最佳，此前该公司上调全年营收预期。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-04/doc-inimequv3893712.shtml",
    "sentiment": "positive",
    "auto": true
  },
  {
    "category": "国际",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "15:13",
    "title": "美国6月职位空缺回落 裁员依然有限",
    "summary": "美国6月职位空缺数量回落，但招聘人数小幅增加，表明进入夏季后企业用工需求总体保持稳定。 美国劳工统计局周二公布的数据显示，6月职位空缺数从5月的754万降至736万。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-04/doc-inimeqvf1830218.shtml",
    "sentiment": "neutral",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "15:06",
    "title": "AMD财报将成为芯片股与成长动量股的关键考验。期权市场释放这些信号",
    "summary": "超威半导体（AMD）将于周二盘后发布财报，当前市场面临一大矛盾：财报业绩有望向好，但股价走势承压。 从历史规律来看，AMD 财报公布后股价波动剧烈...",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-04/doc-inimeqvf1828618.shtml",
    "sentiment": "negative",
    "auto": true
  },
  {
    "category": "内地",
    "date": "2026-08-04",
    "dateCN": "8月4日",
    "time": "15:04",
    "title": "AMD第二季度财报前瞻：市场期待优秀业绩提振半导体行情",
    "summary": "结论先行 AMD（AMD）将于今日收盘后公布其第二季度财报，交易员在关注又一个由AI驱动的增长季度之外，更希望看到公司快速扩张的服务器CPU机会是否仍按计划推进。",
    "soWhat": "",
    "relatedFunds": [],
    "source": "新浪财经",
    "url": "https://finance.sina.com.cn/stock/usstock/c/2026-08-04/doc-inimeknx4016512.shtml",
    "sentiment": "positive",
    "auto": true
  }
];